version: '3.9'

services:
  database:
    image: postgres:latest
    networks:
      network:
        ipv4_address: 10.5.0.4
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=system-diary
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - MAX_LOGIN_ATTEMPTS=0
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 10.5.0.5
    depends_on:
      - database
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.
  
  api:
    image: sd-api
    networks:
      network:
        ipv4_address: 10.5.0.6
    ports:
      - "127.0.0.1:8080:8070"
    depends_on:
      - database
    environment:
      ASPNETCORE_URLS: http://+:8070
  
  frontend:
    image: sd-front
    networks:
      network:
        ipv4_address: 10.5.0.7
    ports:
      - "127.0.0.1:5656:5656"
    depends_on:
      - api
    environment:
      PORT: 5656
      REACT_APP_API_PORT: 8080
      REACT_APP_API_ADDRESS: "localhost"
      
volumes:
  database-data:
  pgadmin:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1